### ISSUE TITLE
I'm sorry not an actual issue - please read below

### ISSUE THREAD

**Issue by ghost** [phhusson/boot-diverter#13]
I'm not sure if development will continue for this. I ended up becoming inspired by your project and made a port to my BLU View 2. I may have some ideas along the way I can make pull requests for

**Comment by phhusson** [comment]
That's been continued to Paralloid
But it has been discontinued since then

**Comment by ghost** [comment]
> That's been continued to Paralloid But it has been discontinued since then
> […](#)
> On January 28, 2023 6:46:40 AM GMT+01:00, DrSimpDevelopment ***@***.***> wrote: I'm not sure if development will continue for this. I ended up becoming inspired by your project and made a port to my BLU View 2. I may have some ideas along the way I can make pull requests for -- Reply to this email directly or view it on GitHub: #13 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

WIll do good sir! My apologies for opening an issue request!
